#!/bin/sh

OPTIONS="\n\n\n󰍃"

CHOSEN=$(echo -e "$OPTIONS" | rofi -dmenu -p "Power Menu" -theme "$HOME/.config/rofi/powermenu.rasi")

case "$CHOSEN" in
    "")
        systemctl poweroff
        ;;
    "")
        systemctl reboot
        ;;
	"")
	xf4lock
	;;
    "󰍃")
        xfce4-session-logout --logout
        ;;
esac
